# Generated by Django 5.0.3 on 2024-04-05 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, help_text='A short bio...', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active'), ('Extra Active', 'Extra Active')], help_text='Select your general level of daily physical activity.', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(blank=True, help_text='Daily calories goal', null=True, validators=[django.core.validators.MinValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gluten-Free', 'Gluten Free'), ('Dairy-Free', 'Dairy Free'), ('Nut-Free', 'Nut Free'), ('Sugar-Free', 'Sugar Free')], default='None', help_text='Any health restrictions you might have', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_profile_url',
            field=models.URLField(blank=True, help_text='Your Facebook profile URL.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Your first name.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('Lose weight', 'Lose Weight'), ('Gain muscle', 'Gain Muscle'), ('Build endurance', 'Build Endurance'), ('Improve flexibility', 'Improve Flexibility'), ('Increase strength', 'Increase Strength')], help_text='Your primary fitness goal', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Goal weight in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Goal weight must be greater than 0.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_profile_url',
            field=models.URLField(blank=True, help_text='Your Instagram profile URL.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Your last name.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_diet',
            field=models.CharField(blank=True, choices=[('Balanced', 'Balanced'), ('High-Protein', 'High Protein'), ('Low-Carb', 'Low Carb'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Balanced', help_text='Select your preferred diet to tailor your nutritional plan.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='images/profile_pictures/'),
        ),
    ]
