# Generated by Django 5.0.3 on 2024-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gluten-Free', 'Gluten Free'), ('Dairy-Free', 'Dairy Free'), ('Nut-Free', 'Nut Free'), ('Sugar-Free', 'Sugar Free')], default='None', help_text='Any health restrictions', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('Lose weight', 'Lose Weight'), ('Gain muscle', 'Gain Muscle'), ('Build endurance', 'Build Endurance'), ('Improve flexibility', 'Improve Flexibility'), ('Increase strength', 'Increase Strength')], help_text='Your primary fitness goal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_diet',
            field=models.CharField(blank=True, choices=[('Balanced', 'Balanced'), ('High-Protein', 'High Protein'), ('Low-Carb', 'Low Carb'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto')], default='Balanced', max_length=15, null=True),
        ),
    ]
