# Generated by Django 5.0.3 on 2024-04-05 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12, null=True)),
                ('intensity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6, null=True)),
                ('type', models.CharField(blank=True, choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('High-Intensity Interval Training', 'Hiit'), ('Flexibility', 'Flexibility'), ('Group Classes', 'Group Classes')], default='Strength Training', max_length=50, null=True)),
                ('equipment_needed', models.CharField(blank=True, help_text='List of equipment needed', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
