# Generated by Django 5.0.3 on 2024-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('High-Intensity Interval Training', 'Hiit'), ('Flexibility', 'Flexibility'), ('Group Classes', 'Group Classes')], default='Strength Training', max_length=50)),
                ('equipment_needed', models.CharField(blank=True, help_text='List of equipment needed', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
