# Generated by Django 5.0.3 on 2024-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('High-Intensity Interval Training', 'Hiit'), ('Flexibility', 'Flexibility'), ('Group Classes', 'Group Classes')], default='Strength Training', max_length=50, null=True),
        ),
    ]
