# Generated by Django 5.0.3 on 2024-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Select the skill level category.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description of the workout.', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='equipment_needed',
            field=models.CharField(blank=True, help_text='List any specific equipment needed for the workout. Leave blank if no equipment is necessary.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Choose the intensity level of the workout.', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(help_text='Name of the exercise', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('High-Intensity Interval Training', 'Hiit'), ('Flexibility', 'Flexibility'), ('Group Classes', 'Group Classes')], default='Strength Training', help_text='Select the type of workout. For example, Cardio, Strength Training, or HIIT.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, help_text='Provide a URL to a video demonstration of the workout.', null=True),
        ),
    ]
