# Generated by Django 5.0.3 on 2024-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakeentry',
            name='unit',
            field=models.CharField(choices=[('Liters', 'Liters')], default='Liters', max_length=20),
            preserve_default=False,
        ),
    ]
