# Generated by Django 5.0.3 on 2024-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_waterintakeentry_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkentry',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterintakeentry',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
