# Generated by Django 4.2.11 on 2024-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_waterintakeentry_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkentry',
            name='unit',
            field=models.CharField(blank=True, choices=[('Liters', 'Liters'), ('Milliliters', 'Milliliters')], default='Milliliters', max_length=11, null=True),
        ),
    ]
